### ISSUE TITLE
Variables from `extraEnv` are added twice in generated resources

### ISSUE THREAD

**Issue by ragnard** [lakekeeper/lakekeeper-charts#29]
The template function `iceberg-catalog.env` already adds variables from `extraEnv`, so code like this:

```yaml
{{- include "iceberg-catalog.env" . | indent 4 }}
{{- if .Values.catalog.extraEnv -}}
{{- toYaml .Values.catalog.extraEnv | nindent 4 }}
{{- end }}
```

will result in duplicate variables in generated resources. This relatively harmless but leads to annoying warnings from helm.

Reproducible by running:

```
helm template foobar charts/lakekeeper --values charts/test.yaml
```

Which will currently produce output like:

```
env:            
  - name: ICEBERG_REST__PG_ENCRYPTION_KEY
    valueFrom:
      secretKeyRef:
        name: foobar-lakekeeper-postgres-encryption
        key: encryptionKey
  - name: SSL_CERT_FILE
    value: /etc/cluster-trust/trust.pem
  
  - name: ICEBERG_REST__PLACEHOLDER
    value: "placeholder"
  - name: SSL_CERT_FILE
    value: /etc/cluster-trust/trust.pem
```
